### ISSUE TITLE
Cannot read property 'year' of undefined

### ISSUE THREAD

**Issue by cfpwastaken** [loumadev/EdupageAPI#2]
My tries doing something with dates in the API (ex. get Homework)
Just gives the error "Cannot read property 'year' of undefined"
`at Edupage.refresh(node_modules\edupage_api\src\Edupage.js:153:5`

**Comment by loumadev** [comment]
Thank you for your feedback. It seems like your school is running some other version/type of Edupage, so you might have some more issues with this API. Since I don't have access to such a school, I can't develop the API that way. I'll do my best to keep it patched, so you can be using it at least partially.

A moment ago I released a new version 0.7.2 (ignore 0.7.1 - I forgot to test it) which should fix your problem.
If the problem persist, please let me know.

**Comment by cfpwastaken** [comment]
Is it because my school is using this schoolname.edupage.org?

**Comment by loumadev** [comment]
I don't think so, I assume each school is using this format (`schoolname.edupage.org`). Edupage is one big mess and that's why it's so hard to implement some general working API which would work for everyone. Everything has multiple possibilities. Some schools may use a different system of lessons, grades... than the others and that's why it's not very stable. In source code I also found there are possibilities for multiple Edupage types.

Did the update fix your problem?
It could be a caching problem only. Your school might not send initial data to work with, so the API has to fetch it manually.
Try using the API and if there are some more bugs, please let me know.

**Comment by cfpwastaken** [comment]
I am currently deving something else I am going to look into it later.

**Comment by ivanhrabcak** [comment]
Hello, I think this issue and issue #5 could be fixed by implementing an alternative way of logging in, same as [here](https://github.com/ivanhrabcak/edupage-api/blob/dffae3886a958946a9de0c1a428fdd1a0ba622a2/edupage_api/__init__.py#L31-L59).  
One of the users of my library encountered a similar [issue](https://github.com/ivanhrabcak/edupage-api/issues/6) where he couldn't log in with the login method you are currently using (and I was using at that time too).
I think this could be solved if you used [this](https://github.com/ivanhrabcak/edupage-api/blob/dffae3886a958946a9de0c1a428fdd1a0ba622a2/edupage_api/__init__.py#L31-L59) method rather than the one you are currently using.
